technology_and_tooling/unit_testing/continuous_integration.md, technology_and_tooling/unit_testing/index.md, technology_and_tooling/unit_testing/introduction.md, technology_and_tooling/unit_testing/setup.md, technology_and_tooling/unit_testing/unit_testing_python.md
Based on https://github.com/OxfordRSE/IntroUnitTestingCourse
=> Add unit testing module

introductory_courses/python/03_writing_and_running_ide.md, introductory_courses/python/09_for_loops.md, introductory_courses/python/10_conditionals.md, introductory_courses/python/11_looping_over_data_sets.md, introductory_courses/python/12_errors_and_exceptions.md, introductory_courses/python/13_writing_functions.md, introductory_courses/python/14_variable_scope.md, introductory_courses/python/15_snake_game.md, introductory_courses/python/index.md
Finish translating course material to new style, and fix a few bugs in older lessons
=> Intro python

high_performance_computing/index.md, introductory_courses/index.md, software_architecture_and_design/index.md, software_project_management/index.md, technology_and_tooling/index.md
Summaries in the md headers exist only for courses, this adds them to themes.
=> Added a summary to themes

introductory_courses/python/01_running_python.md, introductory_courses/python/02_variables_and_types.md, introductory_courses/python/03_writing_and_running_ide.md, introductory_courses/python/04_built_in_functions_and_help.md, introductory_courses/python/05_libraries.md, introductory_courses/python/06_analyzing_and_visualizing_data.md
Trying to touch up the introduction to python course, lessons 1-6, in advance of next weeks course.
There is a small amount wordsmithing, some additions and clarifications and some moderate amount of markdown changes to make it more self-consistent and more consistent with markdown.
While reading this through I think there is room for a degree of restructuring that I will make a follow-up issue for and add to as I do the rest of the touching up but writing them here for now,
- Strings/substrings are introduced prior to slices/lists/arrays/indexing in general and so have to semi-introduce these concepts awkwardly.
- 6. Was in a far better state than the previous lessons but it also repeats some concepts that were previously introduced so could be trimmed slightly.
=> Touch up lessons 1-6 from the python course

software_project_management/continuous_integration/documentation.md
Fix bad link in CI / documentation.md
=> Fix bad link in CI / documentation.md

libraries/pybamm-developer/01_ode.md, libraries/pybamm-developer/02_pde.md, libraries/pybamm-developer/03_spm.md, libraries/pybamm-developer/04_spm_class.md, libraries/pybamm-developer/05_spm_acid.md, libraries/pybamm-developer/06_submodels.md, libraries/pybamm-developer/index.md, libraries/pybamm-developer/spm_template.py
Update/add to the training materials for the PyBaMM developer workshop. So far:
- Small text updates in sections 1-3
- Added sections 4-6
- Added template for SPM model
=> Update PyBaMM developer workshop materials

libraries/pybamm-developer/index.md
=> Add link to slides

software_project_management/continuous_integration/code_coverage.md, software_project_management/continuous_integration/documentation.md, software_project_management/continuous_integration/github_actions.md, technology_and_tooling/packaging_dependency_management/pack_python_03reusing.md, technology_and_tooling/testing/automated_testing.md, technology_and_tooling/testing/diagnosing_issues.md
Small feedback comments from oct's DTC course
=> Small fixes from DTC student feedback.

libraries/index.md, scientific_computing/index.md, scientific_computing/sparse_linear_algebra/01-sparse-matrices.md, software_architecture_and_design/index.md
Gutenberg uses the summary field to populate theme descriptions
=> add summary to scientific prog/libraries themes

CONTRIBUTING.md
- Adds more detail on categories of callout and their use
- Fixes #80
=> fix: Updates CONTRIBUTING.md to include variants of callouts

software_architecture_and_design/procedural/containers_python.md, software_architecture_and_design/procedural/functions_python.md, software_architecture_and_design/procedural/variables_python.md
=> add learning objectives to procedural programming (python) #95

.github/workflows/lint.yaml
https://github.com/alasdairwilson/front-matter-lint  custom gh action to check front matters in the markdown
=> add linting for front matter yaml

high_performance_computing/hpc_openmp/02_intro_openmp.md, high_performance_computing/hpc_openmp/03_parallel_api.md, high_performance_computing/hpc_openmp/04_synchronisation.md, high_performance_computing/hpc_openmp/05_hybrid_parallelism.md
=> Add OpenMP learning objectives

high_performance_computing/hpc_mpi/02_mpi_api.md, high_performance_computing/hpc_mpi/03_communicating_data.md, high_performance_computing/hpc_mpi/04_point_to_point_communication.md, high_performance_computing/hpc_mpi/05_collective_communication.md, high_performance_computing/hpc_mpi/06_non_blocking_communication.md, high_performance_computing/hpc_mpi/07_advanced_communication.md, high_performance_computing/hpc_mpi/08_communication_patterns.md, high_performance_computing/hpc_mpi/09_porting_serial_to_mpi.md, high_performance_computing/hpc_mpi/10_optimising_mpi.md
=> Add MPI learning objectives

software_architecture_and_design/functional/side_effects_cpp.md
=> fix yaml in side_effects_cpp #114

technology_and_tooling/testing/automated_testing.md, technology_and_tooling/testing/index.md, technology_and_tooling/testing/testable_code_fixtures.md
- minor changes to software testing material
- addresses #137
=> 137 revamp testing

scientific_computing/essential_maths/01_graphs.md, scientific_computing/essential_maths/02_indices_and_logs.md, scientific_computing/essential_maths/03_differentiation_1.md, scientific_computing/essential_maths/04_differentiation_2.md, scientific_computing/essential_maths/05_differentiation_3.md, scientific_computing/essential_maths/06_integration_1.md, scientific_computing/essential_maths/07_integration_2.md, scientific_computing/essential_maths/08_complex_numbers.md, scientific_computing/essential_maths/09_differential_equations_1.md, scientific_computing/essential_maths/10_differential_equations_2.md, scientific_computing/essential_maths/11_differential_equations_3.md, scientific_computing/essential_maths/12_linear_algebra_1.md, scientific_computing/essential_maths/13_linear_algebra_2.md, scientific_computing/essential_maths/14_system_1.md, scientific_computing/essential_maths/15_system_2.md, scientific_computing/essential_maths/16_system_3.md, scientific_computing/essential_maths/17_probability_1.md, scientific_computing/essential_maths/18_probability_2.md, scientific_computing/essential_maths/19_probability_3.md, scientific_computing/essential_maths/fig/dtc_hex.svg, scientific_computing/essential_maths/index.md
=> [Revamp] Essential Maths

software_architecture_and_design/procedural/containers_cpp.md, software_architecture_and_design/procedural/functions_cpp.md, software_architecture_and_design/procedural/variables_cpp.md
This PR adds a set of learning outcomes for the C++ Procedural Programming episodes.
Closes #160.
=> Adding learning outcomes to procedural programming C++ sections

scientific_computing/bayesian_inference/index.md, scientific_computing/ode_solvers/index.md
this closes #174 
do check that the descriptions are actually correct though as the last time I took maths was in 2009 and neither ODEs nor Bayesian inference were covered 🤣
=> Course descriptions

scientific_computing/optimisation/01-nonlinear-optimisation.md, scientific_computing/optimisation/02-line-search-methods.md
Closes #166 
This PR adds learning outcomes to Optimisation which is a part of Scientific Computing
=> Add learning outcomes to Optimisation

technology_and_tooling/bash_shell/index.md, technology_and_tooling/best_practices/index.md, technology_and_tooling/docker/index.md, technology_and_tooling/ide/index.md, technology_and_tooling/packaging_dependency_management/index.md, technology_and_tooling/snakemake/index.md, technology_and_tooling/testing/index.md, technology_and_tooling/version_control/index.md
- Goes some way to resolve #173
=> Technology and Tooling Course-Level Outcomes

introductory_courses/python/01_running_python.md, introductory_courses/python/02_variables_and_types.md, introductory_courses/python/03_writing_and_running_ide.md, introductory_courses/python/04_built_in_functions_and_help.md, introductory_courses/python/05_libraries.md, introductory_courses/python/06_analyzing_and_visualizing_data.md, introductory_courses/python/07_pandas_dataframes.md, introductory_courses/python/08_lists.md, introductory_courses/python/09_for_loops.md, introductory_courses/python/10_conditionals.md, introductory_courses/python/11_looping_over_data_sets.md, introductory_courses/python/12_errors_and_exceptions.md, introductory_courses/python/13_writing_functions.md, introductory_courses/python/14_variable_scope.md, introductory_courses/python/15_snake_game.md
- added learning outcomes for all modules of Introductory Courses - Python
- replaced broken render-link to glossary from module 8 (lists) with in-text definition
- address #170
=> Update learning outcomes for Introductory Courses-Python

software_project_management/collaboration/index.md, software_project_management/continuous_integration/index.md
=> Add course-level software project management objectives

software_architecture_and_design/functional/index.md, software_architecture_and_design/object_orientated/index.md, software_architecture_and_design/procedural/index.md
=> Course-level Software Architecture and Design Objectives

cloud_computing/cloud_computing_intro/index.md, cloud_computing/index.md, cloud_computing/migrating_app_to_cloud/app_local_storage.md, cloud_computing/migrating_app_to_cloud/app_migrate_to_aws.md, cloud_computing/migrating_app_to_cloud/app_onprem_limitation.md, cloud_computing/migrating_app_to_cloud/app_remote_storage.md, cloud_computing/migrating_app_to_cloud/app_usecase.md, cloud_computing/migrating_app_to_cloud/aws_services.md, cloud_computing/migrating_app_to_cloud/index.md
- fix: fixed up much of the markdown in the cloud computing course.
=> Fix various markdown mistakes in the cloud computing course.

technology_and_tooling/testing/diagnosing_issues.md, technology_and_tooling/testing/mocking.md, technology_and_tooling/testing/scaling_up.md, technology_and_tooling/testing/testable_code_fixtures.md, technology_and_tooling/unit_testing/unit_testing_python.md
=> fix: use numpy.testing (as npt) for numpy assert calls
