UNIVERSE-HPC/course-material

software_architecture_and_design/procedural/variables_cpp.md
Without the type declaration for full, this code throws an error
=> Declare type for string in C++ procedural variables

CONTRIBUTING.md, LICENSE, README.md
This PR relates to #54, but does not in its current form address all the issues! I wanted to open the PR partly as a way to collaborate on what to include in the documentation :blush:
Honestly, the main change in this PR (other than fixing typos and expanding some instructions) is that I've added the actual text of the CC BY licence in the LICENSE text so that GitHub can recognise the licence correctly. I've added a copyright statement at the top but not sure if that's the correct one (I copied what we have in the website licence).
That's partly because I was uncertain as to who we think will be using this repository. Am I correct in thinking that we expect the main users of this repo to be course contributors and maintainers? I assumed that to be the case because it appears to me that …
=> Expanding documetation

libraries/pybamm-developer/01_ode.md, libraries/pybamm-developer/03_spm.md, libraries/pybamm-developer/04_spm_class.md, libraries/pybamm-developer/05_spm_acid.md
I have now implemented @rtimms comments provided in #72. The main one is that I have now switched the examples to PyBaMM notation. The only small thing is that the model definition uses a reaction rate that needs to be added to the parameter set. I left it as is, as adding to the parameter set is quite a small change and rewriting the examples to match the exchange current density is quite large.
=> Implement comments on PyBaMM dev workshop

high_performance_computing/hpc_intro/01_hpc_intro.md
- presentation link is from software carpentries
- content already covered in course introductory presentation
=> fix: Deletes section on jargon-busting presentation

libraries/index.md, scientific_computing/index.md, technology_and_tooling/index.md
About
---
Closes #93 
- The descriptions for two of the themes were not appearing. The problem seems to be that the summaries need to be specified as multi-line strings (even though they are a single line). This is a small fix to make the summaries appear, it does not tackle why single line strings need to be specified as multiply strings 😅 
- The tech & tooling and software architecture themes had the same description, so I've updated the tech & tooling one.
=> Fix descriptions

high_performance_computing/hpc_aws_slurm_setup/01_flight_solo_setup.md, high_performance_computing/hpc_aws_slurm_setup/index.md, high_performance_computing/index.md
Adds a first draft of a tutorial to set up a training slurm cluster on aws, based on the Flight Solo image and SPack. 
I added it as a single section on a separate course into the HPC theme but, given it's not training material, we may want to put it elsewhere - perhaps a new 'administrative material' theme. That or we would need to incorporate a change into gutenberg which hides certain sections/courses/themes depending on whether the account is a trainee or a trainer, but that would not be a change made to this repo. 
Addresses #99.
=> feat: Adds first draft of slurm-cluster setup tutorial

technology_and_tooling/packaging_dependency_management/pack_python_03reusing.md
This PR makes changes to course section /technology_and_tooling/packaging_dependency_management/pack_python_03reusing in order to fix a number of typos and also to fix the format of the `pyproject.toml` example which is currently incorrect and results in errors.
=> Fix pyproject material

.github/workflows/lint.yaml, technology_and_tooling/packaging_dependency_management/pack_python_04sharing.md
I suddenly realised that i left a fix flag in which would stop autofixable errors from being caught.
=> remove fix option md lint

.github/workflows/lint.yaml
Prevent the workflow running twice every time a push updates a PR.
=> Only lint on push to main

technology_and_tooling/snakemake/additional_features.md, technology_and_tooling/snakemake/advanced.md, technology_and_tooling/snakemake/basics.md, technology_and_tooling/snakemake/index.md, technology_and_tooling/snakemake/setup.md, technology_and_tooling/snakemake/short.md
=> [Revamp] Workflows with Snakemake

libraries/pybamm/01_running_pybamm.md, libraries/pybamm/02_experiments.md, libraries/pybamm/03_parameter_values.md, libraries/pybamm/04_outputs.md, libraries/pybamm/05_using_submodels.md
This PR adds learning outcomes to each chapter of the Intro to PyBaMM course under the Libraries section.
Learning objectives have not been added for the final exercises chapter due to them being open-ended exercises.
Closes #182
=> Add learning outcomes to Intro to PyBaMM course

software_architecture_and_design/procedural/index.md
Changed index pages of Functional Programming and Object-Oriented Programming to show parallel tracks of python and cpp pages side-by-side rather than interspersed, as was already done at Structural Programming.
=> display python and cpp versions side-by-side

scientific_computing/linear_algebra/01-matrix-form-of-equations.md, scientific_computing/linear_algebra/04-LU-decomposition.md, scientific_computing/linear_algebra/06-Cholesky-decomposition.md, scientific_computing/linear_algebra/07-QR-decomposition.md
This PR adds learning outcomes to chapters of the Linear Algebra Solvers course under the Scientific Computing section where they were missing.
Closes #169
=> Add learning outcomes to linear algebra solvers course

scientific_computing/sparse_linear_algebra/01-sparse-matrices.md, scientific_computing/sparse_linear_algebra/02-coo-matrix.md, scientific_computing/sparse_linear_algebra/03-finite-difference.md, scientific_computing/sparse_linear_algebra/04-scipy-sparse.md, scientific_computing/sparse_linear_algebra/06-jacobi-relaxation-methods.md, scientific_computing/sparse_linear_algebra/07-conjugate-gradient-method.md
Closes #161 
This PR adds learning outcomes to the chapters in Sparse Linear Algebra which is a part of Scientific Computing.
=> Add learning outcomes to Sparse Linear Algebra

software_architecture_and_design/functional/higher_order_functions_cpp.md, software_architecture_and_design/functional/higher_order_functions_python.md, software_architecture_and_design/functional/recursion_python.md, software_architecture_and_design/functional/side_effects_python.md
There is one actual bug fix (8705604e235a377df5e9ce958a014e5a1ddfced4) but most of the changes I propose are minor/cosmetic.
In general, I think it's a well-written section, which conveys the advantages of FP clearly and succinctly.
I'm not sure how much we actually want to expand the section. If we do, one idea would be to add an example demonstrating how FP makes it easy to parallelize computations. I'm not sure how to do this in either C++ or Python, but I'd be happy to look into it if we think that's worth it.
(ref. #134)
=> Review of Functional Programming section

software_project_management/continuous_integration/code_coverage.md, software_project_management/continuous_integration/documentation.md, software_project_management/continuous_integration/github_actions.md
- bump outdated GitHub Actions versions.
- update the Codecov instructions for their new web interface.
=> fix: update CI course materials

scientific_computing/essential_maths/01_graphs.md, scientific_computing/essential_maths/02_indices_and_logs.md, scientific_computing/essential_maths/03_differentiation_1.md, scientific_computing/essential_maths/04_differentiation_2.md, scientific_computing/essential_maths/05_differentiation_3.md, scientific_computing/essential_maths/06_integration_1.md, scientific_computing/essential_maths/07_integration_2.md, scientific_computing/essential_maths/08_complex_numbers.md, scientific_computing/essential_maths/09_differential_equations_1.md, scientific_computing/essential_maths/10_differential_equations_2.md, scientific_computing/essential_maths/11_differential_equations_3.md, scientific_computing/essential_maths/12_linear_algebra_1.md, scientific_computing/essential_maths/13_linear_algebra_2.md, scientific_computing/essential_maths/14_system_1.md, scientific_computing/essential_maths/15_system_2.md, scientific_computing/essential_maths/16_system_3.md
This PR adds learning outcomes to all complete (i.e. except for probability) chapters of the Essential Maths course, under the Scientific Computing section.
Closes #165
=> Add learning outcomes to essential maths course

software_project_management/continuous_integration/code_coverage.md, software_project_management/continuous_integration/github_actions.md
I missed this when I updated the other GH Actions.
=> fix: update setup_python action in CI course materials

libraries/pybamm-developer/01_ode.md
This PR fixes the spelling of stoichiometry & stoichiometries throughout the ODEs chapter of the PyBaMM developer course.
Closes #202
=> Fixed stoichiometry/stoichiometries spellings

technology_and_tooling/testing/mocking.md, technology_and_tooling/testing/testable_code_fixtures.md
This PR adds learning outcomes to the Testable Code and Fixtures and Using Mocks in Tests chapters of the Testing course, under Technology and Tooling
Closes #205
=> Add missing learning outcomes to Testing course

software_architecture_and_design/functional/side_effects_cpp.md, software_architecture_and_design/functional/side_effects_python.md
- The fourth rule (birth) wasn't mentioned in the text.
- The bug was described as changing the grid when it shouldn't, but it wasn't actually changing the grid. We now have a different grid example, where the impure version is changing the grid in the wrong way, and we assert that we get the properly changed grid.
- In addition to the intentional state management bug, the impure version didn't properly handle cells dying from under- or overpopulation.
- The `get_neighbours` function was moved to the top of the code files in the C++ versions (that wouldn't compile otherwise).
Also, I changed the text and code to use UK spelling for "neighbours".
=> fix Game-of-Life example in Python and C++
